### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by Udoachim** [Videogamers0/StoryManager#16]
When trying to download a story from one of Literotica's other language sites, the following error occurs:
"Invalid literotica story url format".

Since the sites are structured the same way as the English version, except with the language added to the URL, I believe it shouldn't be too difficult to add this. For example https://german.literotica.com/ instead of https://literotica.com/

Currently, there are these language varieties:
- https://german.literotica.com/
- https://dutch.literotica.com/
- https://spanish.literotica.com/
- https://french.literotica.com/
- https://italian.literotica.com/
- https://romanian.literotica.com/
- https://portuguese.literotica.com/
- https://other.literotica.com/

**Comment by Videogamers0** [comment]
aae612c75f7ab7efdd9eb2944e48a0f76a21e61e

Fixed in v1.0.6: https://github.com/Videogamers0/StoryManager/releases/tag/v1.0.6
