### ISSUE TITLE
Error downloading large story

### ISSUE THREAD

**Issue by justified1gmail** [Videogamers0/StoryManager#4]
Trying to download "Three Square Meals" from author Tefler's page, I get a large error dialog box.
![StoryMgr Error 2023 07 24 Tefler TSM download](https://github.com/Videogamers0/StoryManager/assets/140437014/4ebb6443-d46b-4ba7-bf6f-b671173ad003)

**Comment by Videogamers0** [comment]
f7f8386876d79cc33629e504ff075c1175a53072

This should be fixed now. Version 1.0.2 with the fix is published: https://github.com/Videogamers0/StoryManager/releases
